# Generated by Django 4.2.4 on 2024-12-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='difficulty',
            field=models.CharField(default=4, max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
