# Generated by Django 4.2.4 on 2024-12-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_game', '0002_alter_room_difficulty_alter_room_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='difficulty',
            field=models.CharField(choices=[('easy', 4), ('medium', 5), ('hard', 6)], default='easy', max_length=6),
        ),
    ]
