# Generated by Django 4.2.4 on 2025-01-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_game', '0005_alter_room_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_guess',
            name='feedback_response',
        ),
        migrations.AddField(
            model_name='player_guess',
            name='exact_matches',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player_guess',
            name='matching_numbers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
