# Generated by Django 4.2.4 on 2025-01-01 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_game', '0006_remove_player_guess_feedback_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_guess',
            name='exact_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_guess',
            name='matching_numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_guess',
            name='player_guess',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(regex='^[0-7]*$')]),
        ),
    ]
