# Generated by Django 4.2.4 on 2025-01-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_game', '0008_remove_room_participants_room_max_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_guess',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='room_score',
            old_name='username',
            new_name='user',
        ),
    ]
